### ISSUE TITLE
Case mismatch in class names

### ISSUE THREAD

**Issue by alexloehner** [mktcode/caitcha-bundle#1]
The Class Source file is named "MktcodeCaitchaBundle.php", note the lower case "c" in the word "code".
The Class name itself in the source file is called "MktCodeCaitchaBundle.php" with upper case "C".

1. When following your installation instructions, this causes a "Class 'MktCode\CaitchaBundle\MktCodeCaitchaBundle' not found"

2. When changing the "C" to "c" in AppKernel.php, then it causes a "Case mismatch between loaded and declared class names: MktCode\CaitchaBundle\MktcodeCaitchaBundle vs MktCode\CaitchaBundle\MktCodeCaitchaBundle"

So, please fix your namings.

**Comment by mktcode** [comment]
Wow, did not expect someone to stumble upon this repo... :)
Thank you for the feedback. I fixed this, so now it should behave as expected.

**Comment by alexloehner** [comment]
Thanks, THIS issue is fixed.
